//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "texpense", table_name = "account")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_account: i32,
    #[sea_orm(unique)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((16, 2)))", nullable)]
    pub amount: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
