//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::account::Entity as Account;
pub use super::category::Entity as Category;
pub use super::payment::Entity as Payment;
pub use super::template::Entity as Template;
pub use super::transaction::Entity as Transaction;
